version: '3.8'

services:
  testagent:
    build: .
    working_dir: /app
    environment:
      # Required API Keys
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      
      # Firebase Configuration
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      
      # GitHub Repository Info
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - PR_NUMBER=${PR_NUMBER}
      - HEAD_SHA=${HEAD_SHA}
      - BASE_SHA=${BASE_SHA}
      
      # Git diff data (base64 encoded)
      - DIFF_B64=${DIFF_B64}
      
      # Configuration
      - LINE_THRESHOLD=200
      - MODEL=${MODEL:-o3-mini}
      
    volumes:
      # Mount local directory for development
      - .:/app
      
    # Override command for different operations
    command: python scripts/ai_review.py
