version: '3.8'

services:
  github-workflows:
    build: .
    image: github-workflows:latest
    container_name: github-workflows
    environment:
      - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LINE_THRESHOLD=${LINE_THRESHOLD:-200}
      - CHANGES_THRESHOLD=${CHANGES_THRESHOLD:-5}
    volumes:
      - .:/app/workspace
      - ./test-files:/app/test-files
    ports:
      - "8080:8080"
    command: health

  # Optional: Web interface for monitoring
  workflow-api:
    build: .
    image: github-workflows:latest
    container_name: workflow-api
    environment:
      - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8081:8080"
    command: bash -c "python3 -m http.server 8080"
    volumes:
      - ./logs:/app/logs

  # Development container with bash
  dev:
    build: .
    image: github-workflows:latest
    container_name: github-workflows-dev
    environment:
      - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app/workspace
      - ./test-files:/app/test-files
    command: bash
    stdin_open: true
    tty: true
