name: branches-develop
on:
  push:
    branches: develop
jobs:
  build-android-apk-dev:
    runs-on: ubuntu-latest
    environment:
      name: Develop-Android
    container:
      image: public.ecr.aws/j7e3x4p5/flutter-build:51
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Set Build Number
        shell: sh
        run: ./set_build_number
        env:
          BASE_NUMBER: 1000
          GITHUB_ENV: $GITHUB_ENV
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
      - name: Upload Dev APK
        run: |-
          ./download_keystore
          ./setup_flutter

          # Create symlink from expected to actual path
          mkdir -p /root/fvm
          ln -sfn /github/home/fvm/default /root/fvm/default
            
          # Ensure flutter is in PATH
          export PATH=$PATH:/root/fvm/default/bin

          ./flutterfire_configure_android
          ./run_build_runner_packages
          ./run_flutter_gen_l10n
          ./build_apk
          ./upload_to_firebase
          ./artefact_output_path
        env:
          KEYSTORE_ALIAS: ${{ vars.KEYSTORE_ALIAS }}
          FLAVOR_NAME: ${{ vars.FLAVOR_NAME }}
          FIREBASE_PROJECT: ${{ vars.FIREBASE_PROJECT }}
          FIREBASE_APP: ${{ vars.FIREBASE_APP }}
          ANDROID_PACKAGE: ${{ vars.ANDROID_PACKAGE }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          BUILD_NAME: "1.0.0"
      - uses: actions/upload-artifact@v4.1.0
        with:
          name: build-android-apk-dev
          path: |-
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/apk/*/*/*.apk
            build/reports/**
  build-ios-dev:
    runs-on:
      - self-hosted
      - macos
    environment:
      name: Develop-IOS
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set Build Number
        shell: sh
        run: ./set_build_number
        env:
          BASE_NUMBER: 1000
          GITHUB_ENV: $GITHUB_ENV
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
      - name: Upload Dev IPA
        run: |-
          ./setup_flutter
          ./setup_fastlane
          ./flutterfire_configure_ios
          ./run_build_runner_packages
          ./run_flutter_gen_l10n
          ./upload_to_testflight
        env:
          BUNDLE_ID: ${{ vars.BUNDLE_ID }}
          TEAM_ID: ${{ vars.TEAM_ID }}
          SCHEME: ${{ vars.SCHEME }}
          APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
          API_KEY_ID: ${{ vars.API_KEY_ID }}
          API_KEY_ISSUER: ${{ vars.API_KEY_ISSUER }}
          IS_CLIENT_ACCOUNT: ${{ vars.IS_CLIENT_ACCOUNT }}
          FIREBASE_PROJECT: ${{ vars.FIREBASE_PROJECT }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          BUILD_NAME: "1.0.0"
