name: Pull Request

on:
  pull_request:
    branches:
      - "**"
jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    environment:
      name: Develop-Android
    container:
      image: public.ecr.aws/j7e3x4p5/flutter-build:51
    steps:
      - uses: actions/checkout@v4
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Build APK
        run: |-
          ./download_keystore
          ./setup_flutter

          # Create symlink from expected to actual path
          mkdir -p /root/fvm
          ln -sfn /github/home/fvm/default /root/fvm/default
          
          # Ensure flutter is in PATH
          export PATH=$PATH:/root/fvm/default/bin

          ./flutterfire_configure_android
          ./run_build_runner_packages
          ./run_flutter_gen_l10n
          ./build_apk
        env:
          KEYSTORE_ALIAS: ${{ vars.KEYSTORE_ALIAS }}
          FLAVOR_NAME: ${{ vars.FLAVOR_NAME }}
          FIREBASE_PROJECT: ${{ vars.FIREBASE_PROJECT }}
          FIREBASE_APP: ${{ vars.FIREBASE_APP }}
          ANDROID_PACKAGE: ${{ vars.ANDROID_PACKAGE }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  build-ios:
    name: Build iOS
    runs-on:
      - self-hosted
      - macos
    environment:
      name: Develop-iOS
    steps:
      - uses: actions/checkout@v4
      - name: Build IPA
        run: |-
          ./setup_flutter
          ./setup_fastlane
          ./flutterfire_configure_ios
          ./run_build_runner_packages
          ./run_flutter_gen_l10n
          ./build_adhoc
        env:
          BUNDLE_ID: ${{ vars.BUNDLE_ID }}
          TEAM_ID: ${{ vars.TEAM_ID }}
          SCHEME: ${{ vars.SCHEME }}
          APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
          API_KEY_ID: ${{ vars.API_KEY_ID }}
          API_KEY_ISSUER: ${{ vars.API_KEY_ISSUER }}
          IS_CLIENT_ACCOUNT: ${{ vars.IS_CLIENT_ACCOUNT }}
          FIREBASE_PROJECT: ${{ vars.FIREBASE_PROJECT }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
